alphagov/verify-metadata-controller

pkg/controller/metadata/metadata_controller.go
This is useful for adding things such as `NetworkPolicies` which require
a CIDR rather than just an IP.
=> Add HSM CIDR to generated metadata secret

pkg/controller/metadata/metadata_controller.go
istio likes things to have nice names, so we name the service and
container ports "http" so that they play nice with the mesh
=> name the ports

chart/templates/cert-request-production.yaml, chart/templates/cert-request-test.yaml
This will add two CertificateRequests to the VMC to generate Root CA Secrets for "verify-root-ca-production" (that will be used for production deployments) and "verify-root-ca-test" (used for non-production deployments)
=> adds root CertificateRequests for prod/test CA generation

mdgen/src/main/java/uk/gov/ida/mdgen/MetadataGenerator.java
We were using the wrong certs as our signing and encryption certs in connector metadata, this fixes that.
=> Use saml signing certs for connector metadata

chart/templates/verify_v1beta1_certificaterequest.yaml, chart/templates/verify_v1beta1_metadata.yaml, config/crds/verify_v1beta1_certificaterequest.yaml, config/crds/verify_v1beta1_metadata.yaml, pkg/apis/verify/v1beta1/certificaterequest_types.go, pkg/controller/certificaterequest/certificaterequest_controller.go
CACert was not being set on the CertRequest before being passed to
CreateChainCertificate.
Standandize on CACert over caCert since this was being used in more
places already
=> fix inconsistant use of CACert and pass to tool

pkg/controller/certificaterequest/certificaterequest_controller.go, pkg/controller/certificaterequest/certificaterequest_controller_test.go, pkg/controller/metadata/metadata_controller.go, pkg/controller/metadata/metadata_controller_test.go
Adds the following values to the generated metdata Secret:
* metadataCACerts: concat list of PEM CA certs for the metadata signing
* metadataCATruststore: truststore version of above for java-land
* metadataCATruststoreBase64: base64 version of above as that is what
the app accepts
* metadataCATruststorePassword: password for above
Adds tests to cover some of the recent changes and the CA cert bundling
=> adds CA chain value to generated metadata secret

cloudhsmtool/src/main/java/uk/gov/ida/cloudhsmtool/CreateChainedCertificate.java, cloudhsmtool/src/main/java/uk/gov/ida/cloudhsmtool/CreateSelfSignedCertificate.java
When we create a CA cert using the [cloudhsmtool](https://github.com/alphagov/verify-metadata-controller/blob/master/cloudhsmtool/README.md), the x509 Extension section shows:
```
Extensions
basicConstraints :
cA=true
```
According to [X509 Extension Spec](https://access.redhat.com/documentation/en-US/Red_Hat_Certificate_System/8.0/html/Admin_Guide/Standard_X.509_v3_Certificate_Extensions.html) (search for basicConstraints), this extension must be marked critical so that it looks like:
```
Extensions
basicConstraints CRITICAL:
cA=true
```
This PR will surface that CRITICAL keyword.
=> Mark basicContraints x509 extension as critical for CA certs

config/default/kustomization.yaml
This was probably fine when Chris wrote it in February, but since then the
newest release of Kustomization has broken things:
https://github.com/kubernetes-sigs/kustomize/issues/1373
=> kustomization: Work with v3

config/default/kustomization.yaml, config/rbac/auth_proxy_role_binding.yaml
It seems the "default" namespace is replaced with null by Kustomize for some
reason.
This seems to allow the kubectl to be applied, though may not work correctly?
=> Kustomization: Don't use default namespace

pkg/controller/metadata/metadata_controller.go
This fairly useless piece of logging is to trigger a new release of the
VMC so we can check the release process.
=> BAU Update logging to test release process

chart/templates/verify_v1beta1_metadata.yaml, config/crds/verify_v1beta1_metadata.yaml, mdgen/docker/integration_tests/features/feature/launch.feature, mdgen/docker/integration_tests/features/step_definitions/launch_steps.rb, mdgen/src/main/java/uk/gov/ida/mdgen/MetadataGenerator.java, pkg/apis/verify/v1beta1/metadata_types.go, pkg/controller/metadata/metadata_controller.go, pkg/controller/metadata/metadata_controller_test.go, pkg/hsm/awscloudhsm/cloudhsm.go, pkg/hsm/client.go
Change the timestamp to be RFC1123Z rather than to use days,
It also adds them to the metadata secrets.
We want todo this so we can check the certificate expirer externally so we can later regenerate the certificates when they expire.
=> EID-1615: Store the valid until 

pkg/controller/metadata/metadata_controller.go, pkg/controller/metadata/metadata_controller_test.go
Add logic to pick out the values saved in the metadata secrets detailing the expirey of the metadata, check it and if we are over half way through the metadatas life cycle then trigger regeneration of the metadata / certificates.
=> EID-1616: Added in logic to determine if we should regenerate metadata if metadata is at least halfway through its lifecycle

chart/templates/vmc-statefulset.yaml
adds the `talksToHsm: true` label to the vmc pod
a NetworkPolicy restricts access to cloudhsm network unless it has the
blessed talksToHsm:true label on the Pod.
=> add the blessed talksToHsm label to the VMC pod

pkg/controller/metadata/metadata_controller.go, pkg/controller/metadata/metadata_controller_test.go
We publish our Proxy Node certificate authorities for Proxy Node metadata at:
https://test-integration-proxy-node.london.verify.govsvc.uk/ServiceMetadataSigningCertificates
Similarly, we publish Connector Node certificate authorities for Connector Node metadata at: 
https://test-integration-connector.london.verify.govsvc.uk/ConnectorMetadataSigningCertificates
These certs are derived from a secret stored in the k8s cluster - currently we store not only the CA certs, but also the "leaf" metadata signing cert in the secret. We don't need to show the leaf cert, and subsequently have to stop it showing on the urls above.
This PR removes the leaf cert saved to the secret.
Another PR will remove the filtering we have to do to stop it appearing.
=> Remove leaf cert from set of CA certs saved to metadata secret

ci/sandbox/deploy-pipeline.yaml, ci/sandbox/release-pipeline.yaml, ci/verify/release-pipeline.yaml
We (autom8) want to be able to block access from the public internet to
the Harbor API. Previously we had done this by implementing a IP
safelist. Given some changes we're expecting to make to Istio we will be
unable to see the original IP of the user at the point that our current
safelist performs its checks.
We have decided to block API access entirely (except from within the
cluster).
Our `concourse-harbor-resource` now defaults to using the internal
service to talk to the Harbor API so all we need to do is remove the
explicit setting of `harbor.url`.
=> Use the internal service for the Harbor API

ci/verify/release-pipeline.yaml
the vmc requires a cloudhsm-client-image, this was previously being
pulled from the proxy-node's build, but that creates a strange dependecy
on the proxy-node's build pipeline in another namespace.
instead, build it ourself here.
=> vmc requires a cloudhsm-client-image

Dockerfile, cloudhsmtool/build.gradle, cloudhsmtool/src/main/java/uk/gov/ida/cloudhsmtool/CloudHSMTool.java, cloudhsmtool/src/main/java/uk/gov/ida/cloudhsmtool/CreateSelfSignedCertificate.java, cloudhsmtool/src/main/java/uk/gov/ida/cloudhsmtool/GenRSA.java, mdgen/build.gradle
There are currently no real tests* for the changes being made here other than to test them out in the sandbox. These two commits are currently pushed to the sandbox branch of the VMC and I have observed both `cloudhsmtool` and `mdgen` working as intented.
If you want to check them for yourself you can do so by:
Jumping on to the VMC application and running the cloudhsmtool directly - this will create a new RSA keypair in the sandbox HSM.
```
$ gds sandbox k -n sandbox-metadata-controller exec -it v1-vmc-0 /bin/bash
$ cloudhsmtool/build/install/cloudhsmtool/bin/cloudhsmtool genrsa <a key alias you made up> 
```
Regenerating some metadata succesfully (already on the VMC box):
Tail the VMC logs in one terminal window
```
gds sandbox k -n sandbox-metadata-controller logs v1-vmc-0 controller …
```
=> EID-1941: Upgrade cloudhsm client to v3.0.0

ci/sandbox/release-pipeline.yaml
So we can push to sandbox branches without a PR.
=> sandbox ci: Use git resource instead of github

README.md, cloudhsmtool/Dockerfile, mdgen/docker/Dockerfile
We had to rebuild the sandbox CloudHSM ingress so we've got a new LB and
therefore a new domain for it.
=> Update the sandbox CloudHSM ingress

mdgen/src/main/resources/proxy_template.xml.mustache
Spaces in the VMC `proxy_template.xml.mustache` are reported  to be causing Netherlands to have issues parsing our Proxy Node response, see https://govuk.zendesk.com/agent/tickets/3950985.
Remove these spaces.
=> ZEN-3950985 Proxy Node metadata spaces

mdgen/build.gradle
The [VMC build pipeline](https://ci.london.verify.govsvc.uk/teams/metadata-controller/pipelines/release/jobs/build-vmc) is failing as this snapshot dependency doesn't exist - bump the version to the same as the cloudhsmtool
=> BAU Upgrade VMC mdgen snakeyaml

Dockerfile
During PR review we removed settings.gradle from sub-projects.
This was never reflected in Dockerfile and the build breaks building the docker image.
This is an identical PR to another which caused a pipeline failure as approver was not a GDS trusted developer, see https://ci.london.verify.govsvc.uk/teams/metadata-controller/pipelines/release/jobs/build-vmc/builds/10
=> EID-1943 rm refs to settings.gradle from Dockerfile

mdgen/src/main/java/uk/gov/ida/mdgen/MetadataGenerator.java, mdgen/src/test/java/uk/gov/ida/mdgen/MetadataGeneratorTest.java
We started using the `http://www.w3.org/2007/05/xmldsig-more#sha384-rsa-MGF1` siging algo for existing RSA keys in HSM, and this is resulting in Connector Nodes being unable to accept our Proxy Node metadata.
Use the BAU metadata signing algo of `http://www.w3.org/2001/04/xmldsig-more#rsa-sha25` for existing BAU RSA keys.
Multi-country Proxy Node metadata uses EC keys and will not be affected.
=> BAU Restore RSA-SHA256 Metadata Signing Algo for RSA keys

mdgen/src/main/resources/connector_template.xml.mustache
We send this SPType in our eidas SAML Request and the spec forbids it being present in both metadata and request.
Needed to progress on a DE middleware upgrade spike
=> BAU Remove SpType of 'public'

chart/templates/cert-request-production-a1.yaml
Made a copy of cert-request-test-a1.yaml but replaced test with production in the filename, and removed “test” from the yaml. This will create a new root CA cert, that has been created by an EC key
=> EID-1960: Production request cert

chart/templates/vmc-statefulset.yaml, ci/sandbox/release-pipeline.yaml, ci/verify/deploy-pipeline.yaml, ci/verify/release-pipeline.yaml
Add this even to pods that don't explicitly reference DockerHub because they
will most likely get containers that do injected by Istio anyway.
This secret is provided by GSP. Do not merge until GSP v1.1.686 has
successfully rolled out to verify.
=> Use dockerhubpull secrets to access DockerHub
